baseURL = "http://qnot.org/"
languageCode = "en-us"
pygmentsStyle = "monokai"
pygmentsUseClasses = true

[permalinks]
  blog = "/:year/:month/:day/:title/"

[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  Author = "Andrew E. Bruno"
